# docker-compose.yml
services:
  shift-planner:
    build: .
    container_name: shift_planner
    env_file:
      - .env
    ports:
      - "8501:8501"
    volumes:
      - ./shifts.db:/app/shifts.db
      - ./.streamlit:/app/.streamlit
    command: streamlit run main.py --server.port=${SERVER_PORT:-8501} --server.address=0.0.0.0
    restart: unless-stopped